name: My First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fist_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ vars.WHO_TO_GREET }} 👋 from ${{ github.actor }}"
          echo "My secret is 🤫 ${{ secrets.MY_SECRET }}"
          echo "Current branch is '${{ github.ref }}'"
          
